# CalVer versioning: YYYY.MINOR.PATCH
# Bump PACN_VERSION_MONTH / PACN_VERSION_PATCH for releases.
set(PACN_VERSION_YEAR  2026)
set(PACN_VERSION_MONTH 6)
set(PACN_VERSION_PATCH 0)
set(PACN_VERSION "${PACN_VERSION_YEAR}.${PACN_VERSION_MONTH}.${PACN_VERSION_PATCH}")
